name: itv123

on:
  schedule:
    - cron: '0 2,6,10,14,18,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run itv123
        run: python ${{ github.workspace }}/itv.py

      - name: Run cctv123
        run: python ${{ github.workspace }}/cctv.py
        
      - name: Run weishi123
        run: python ${{ github.workspace }}/weishi.py
        
      - name: Run qita123
        run: python ${{ github.workspace }}/qita.py
        
      - name: 提交更改
        run: |
          git config --local user.email "longlonglaile1@126.com"
          git config --local user.name "longlonglaile2"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
